[tool.autoflake]
remove-all-unused-imports = true
remove-unused-variables = false
expand-star-imports = false
ignore-init-module-imports = true
in-place = true
recursive = true
exclude = ["env", "venv", "__pycache__"]
paths = ["app"]

[tool.ruff]
line-length = 88
target-version = "py311"  # or your version
src = ["app"]
exclude = ["env", "venv", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.black]
line-length = 79
include = 'app\/.*\.py$'
exclude = '''
/(
    .git
    | .pytest_cache
    | build
    | dist
    | migrations
)/
'''
