"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os

os.environ['MACOSX_DEPLOYMENT_TARGET'] = '14.0'

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    ('assets', [
        'assets/arrow-back-icon.svg',
        'assets/close-icon.svg',
        'assets/dice-icon.svg',
        'assets/folder-icon.svg',
        'assets/freq-icon.svg',
        'assets/heart-icon-fill.svg',
        'assets/heart-icon.svg',
        'assets/list-icon.svg',
        'assets/power-icon.svg',
        'assets/refresh-icon.svg',
        'assets/settings-icon.svg',
        'assets/stereo-icon.svg',
        'assets/switch-icon.svg',
    ]),
]
OPTIONS = {
    'argv_emulation': False,
    'includes': ['Cocoa'],
    'packages': ['app',
                 'sqlmodel',
                 'numpy',
                 'librosa',
                 'soundfile',
                 'watchdog',
                 'sqlite3',
                 ],
    'arch': 'universal2',
    'plist': {
        'CFBundleName': 'Hit Crate',
        'CFBundleDisplayName': 'Hit Crate',
        'CFBundleIdentifier': 'com.aidanrodriguez.hitcrate',
        'CFBundleVersion': '1.1.2',
        'CFBundleShortVersionString': '1.1.2'
    },
    'iconfile': 'assets/vinyl-icon.icns',
    'excludes': ['wheel', 'tkinter', 'matplotlib', 'PyInstaller'],
    'semi_standalone': False,
    'optimize': True,
    'frameworks': [
        '/Library/Frameworks/Python.framework/Versions/3.13'
    ],
    'resources': [
        '/opt/homebrew/Cellar/libsndfile/1.2.2_1/lib/libsndfile.dylib'
    ]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    name="Hit Crate",
    version="1.1.2",
    author="Aidan Rodriguez",
    author_email="aidan@aidanrodriguez.com",
    license="MIT",
    setup_requires=['py2app'],
)
