"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app/main.py']
DATA_FILES = [
    ('assets', [
        'app/frontend/assets/arrow-back-icon.svg',
        'app/frontend/assets/close-icon.svg',
        'app/frontend/assets/folder-icon.svg',
        'app/frontend/assets/freq-icon.svg',
        'app/frontend/assets/heart-icon-fill.svg',
        'app/frontend/assets/heart-icon.svg',
        'app/frontend/assets/settings-icon.svg',
        'app/frontend/assets/stereo-icon.svg',
    ]),
]
OPTIONS = {
    'argv_emulation': False,  # For macOS GUI apps to properly handle sys.argv
    'includes': ['Cocoa'],   # Ensure Cocoa is explicitly included
    'frameworks': ['/System/Library/Frameworks/Cocoa.framework'],  # Explicitly link Cocoa
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    name="Hit Crate",
    author="Aidan Rodriguez",
    author_email="aidan@aidanrodriguez.com",
    license="MIT",
    setup_requires=['py2app'],
)
