"""add other props

Revision ID: 918a9fd9e7db
Revises: ad341eedd4da
Create Date: 2025-04-26 18:32:40.067157

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '918a9fd9e7db'
down_revision: Union[str, None] = 'ad341eedd4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('slope', sa.BLOB(), nullable=True))
    op.add_column('sample', sa.Column('fundamental', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'fundamental')
    op.drop_column('sample', 'slope')
    # ### end Alembic commands ###
