"""add relationships

Revision ID: 9655632ae1c8
Revises: 956282f979bc
Create Date: 2025-04-29 10:16:16.356686

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9655632ae1c8"
down_revision: Union[str, None] = "956282f979bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sample", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("parent_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )
        batch_op.create_foreign_key(
            "fk_sample_parent_path_directory",  # it's good to name your FK
            "directory",
            ["parent_path"],
            ["path"],
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sample", type_="foreignkey")
    op.drop_column("sample", "parent_path")
    # ### end Alembic commands ###
