"""fix mfcc

Revision ID: 997077142f86
Revises: 9655632ae1c8
Create Date: 2025-04-29 17:34:14.854680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997077142f86'
down_revision: Union[str, None] = '9655632ae1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("sample", "mfcc")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sample", sa.Column("mfcc", sa.BLOB(), nullable=False))
    # ### end Alembic commands ###
