"""fix mfcc not null

Revision ID: a56170a7777f
Revises: 997077142f86
Create Date: 2025-04-29 17:36:30.641918

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a56170a7777f"
down_revision: Union[str, None] = "997077142f86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("sample", sa.Column("mfcc", sa.BLOB(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sample", sa.Column("mfcc", sa.BLOB(), nullable=False))
    op.drop_column("sample", "mfcc")
    # ### end Alembic commands ###
