"""add rolloff

Revision ID: a6b78af2153d
Revises: d2266be92215
Create Date: 2025-05-07 13:50:18.546833

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a6b78af2153d'
down_revision: Union[str, None] = 'd2266be92215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('rolloff', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'rolloff')
    # ### end Alembic commands ###
