"""create table

Revision ID: ad341eedd4da
Revises: 
Create Date: 2025-04-26 18:30:14.181453

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ad341eedd4da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('format', sa.Enum('wav', 'mp3', name='audioformat'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('lufs', sa.Float(), nullable=False),
    sa.Column('stereo_width', sa.Float(), nullable=False),
    sa.Column('spectral_curve', sa.BLOB(), nullable=True),
    sa.Column('loudness', sa.BLOB(), nullable=True),
    sa.Column('rolloff', sa.BLOB(), nullable=True),
    sa.Column('spectogram', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample')
    # ### end Alembic commands ###
