"""mfcc simple

Revision ID: b2d92ebfc325
Revises: fec9e1b24247
Create Date: 2025-04-27 16:54:36.275840

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2d92ebfc325"
down_revision: Union[str, None] = "fec9e1b24247"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sample", sa.Column("mfcc", sa.BLOB(), nullable=True))
    op.drop_column("sample", "spectogram")
    op.drop_column("sample", "slope")
    op.drop_column("sample", "loudness")
    op.drop_column("sample", "spectral_curve")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sample", sa.Column("spectral_curve", sa.BLOB(), nullable=True))
    op.add_column("sample", sa.Column("loudness", sa.BLOB(), nullable=True))
    op.add_column("sample", sa.Column("slope", sa.BLOB(), nullable=True))
    op.add_column("sample", sa.Column("spectogram", sa.BLOB(), nullable=True))
    op.drop_column("sample", "mfcc")
    # ### end Alembic commands ###
