"""add favorites

Revision ID: d2266be92215
Revises: a56170a7777f
Create Date: 2025-05-01 11:02:12.892517

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd2266be92215'
down_revision: Union[str, None] = 'a56170a7777f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column("sample", sa.Column("is_favorite", sa.Boolean(), nullable=False, server_default=sa.text("0")))
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("sample", "is_favorite")
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
