"""spectral centroid

Revision ID: d7309019abc2
Revises: b2d92ebfc325
Create Date: 2025-04-27 17:40:49.473257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7309019abc2'
down_revision: Union[str, None] = 'b2d92ebfc325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('spectral_centroid', sa.Float(), nullable=False))
    op.drop_column('sample', 'rolloff')
    op.drop_column('sample', 'fundamental')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('fundamental', sa.BLOB(), nullable=True))
    op.add_column('sample', sa.Column('rolloff', sa.BLOB(), nullable=True))
    op.drop_column('sample', 'spectral_centroid')
    # ### end Alembic commands ###
