"""switch lufs to rms

Revision ID: fec9e1b24247
Revises: 918a9fd9e7db
Create Date: 2025-04-27 12:13:53.026726

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fec9e1b24247'
down_revision: Union[str, None] = '918a9fd9e7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('rms', sa.Float(), nullable=False))
    op.drop_column('sample', 'lufs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('lufs', sa.FLOAT(), nullable=False))
    op.drop_column('sample', 'rms')
    # ### end Alembic commands ###
