name: PUSH

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout code
      - name: Run Linter (Ruff)
        run: ruff check --fix .  # Run ruff linter
